export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const CREATE_SUCCESS = 'CREATE_SUCCESS';
export const EDIT_SUCCESS = 'EDIT_SUCCESS';
export const DELETE_SUCCESS = 'DELETE_SUCCESS';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const REDIRECTED = 'REDIRECTED';

export const LOGIN_FAIL = 'LOGIN_FAIL';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const AJAX_BEGIN = 'AJAX_BEGIN';
export const AJAX_ERROR = 'AJAX_ERROR';